name: Commitlint
on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened, edited]
  merge_group:
  workflow_dispatch:
permissions: { contents: read }
concurrency:
  group: commitlint-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  commitlint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: codywilliamson/commit-guard@v0.3.0
        with:
          mode: commits
          token: ${{ github.token }}
